package me.bottdev.meshdi.api;

/// Represents a compiled definition of a component, usually generated by the annotation processor.
///
/// Component definitions describe how a specific component should be bound into the DI container.
public interface ComponentDefinition<T> {

    /// Creates and returns a [BindingBuilder] configured for this component.
    ///
    /// @return a new binding builder initialized with the component's metadata
    BindingBuilder<T> create();

}
